# Generated by Django 5.0.7 on 2024-07-16 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0003_alter_aluguel_data_aluguel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='livro',
            name='resumo',
            field=models.TextField(blank=True),
        ),
    ]
