# Generated by Django 5.0.7 on 2024-07-16 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0004_remove_livro_data_publicacao_remove_livro_disponivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluguel',
            name='data_devolucao_prevista',
            field=models.DateField(default=datetime.datetime(2024, 7, 30, 3, 44, 31, 671130, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='aluguel',
            name='multa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
