# Generated by Django 5.0.7 on 2024-07-16 03:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0005_aluguel_data_devolucao_prevista_aluguel_multa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluguel',
            name='data_devolucao_prevista',
            field=models.DateField(default=datetime.datetime(2024, 7, 30, 3, 52, 45, 268372, tzinfo=datetime.timezone.utc)),
        ),
    ]
